on:
  push:
    branch:
      - master

name: 'Trigger: Check spelling'

jobs:
  proselint:
    name: Proselint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run ShellCheck
      uses: amperser/proselint@master
