# Shellcheck any shell files in the repository

on:
  push:
    branches:
      - master

name: 'Trigger: Push action'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run ShellCheck
      uses: stunning-engine/.github/workflows/shellcheck.yml
